name: golintr
author: norwd
description: "Lint your code using golint"

branding:
  icon: check-circle
  color: green

inputs:
  path:
    description: 'Path used by golint command'
    required: false
    default: './...'

outputs:
  errors:
    description: 'The golint output if the command fail'
    value: ${{ steps.golint.outputs.errors }}

runs:
  using: composite
  steps:
    - id: install
      name: "Install `golint`"
      shell: bash
      run: go install golang.org/x/lint/golint@latest

    - id: golint
      name: "Run `golint`"
      shell: bash
      env:
        GOLINT_PATH: ${{ inputs.path }}
      run: |
        {
          echo "errors<<EOF"
          ~/go/bin/golint -set_exit_status "${GOLINT_PATH}" || true
          echo "EOF"
        } >> "${GITHUB_OUTPUT}"

    - if: steps.golint.outputs.errors != ''
      name: "Display Errors"
      uses: norwd/grawk@main
      with:
        input: ${{ steps.golint.outputs.errors }}
        program: |
          {
            file=$1
            line=$2
            title="Go Lint Error"

            $1=""
            $2=""
            $3=""

            print "::error file=" file ",line=" line ",title=" title "::" $0
          }

    - if: steps.golint.outputs.errors != ''
      name: "Exit With Error Code 1"
      shell: bash
      run: exit 1
